#!/usr/bin/env bash
# Stand up a self-hosted Specboards with one command.
#
#   ./setup.sh              # build, migrate, start; http://localhost:3000
#   ./setup.sh --stop       # stop the stack, keep the data
#   ./setup.sh --destroy    # stop and delete the database volume
#
# Everything this does by hand, a person previously had to do by reading:
# generate a secret, write infra/.env, bring up compose, discover the database
# was empty, find the migration command in a different section of the README,
# and run that too. The 2026-08-31 clean-machine run stopped on each of those in
# turn, so they are automated here rather than documented harder.
#
# Re-running is safe: an existing infra/.env is never overwritten, and the
# migration runner is idempotent.
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$root"

compose=(docker compose -f infra/docker-compose.yml)
env_file="infra/.env"

case "${1:-}" in
  --stop)
    exec "${compose[@]}" down
    ;;
  --destroy)
    # -v drops the named volume, which is the database. Ask first: this is the
    # one thing here that destroys data someone may care about.
    printf 'This deletes the Specboards database volume and everything in it.\n'
    read -r -p 'Type "destroy" to confirm: ' reply
    [ "$reply" = "destroy" ] || { echo "Aborted."; exit 1; }
    exec "${compose[@]}" down -v
    ;;
  "" | --start) ;;
  *)
    echo "usage: ./setup.sh [--stop|--destroy]" >&2
    exit 64
    ;;
esac

# --- prerequisites ----------------------------------------------------------
# Checked up front and reported together: finding out about the second missing
# tool after a four-minute image build is a bad way to learn it.
missing=()
command -v docker >/dev/null 2>&1 || missing+=("docker (https://docs.docker.com/get-docker/)")
docker compose version >/dev/null 2>&1 || missing+=("docker compose v2 (bundled with Docker Desktop)")
if [ ${#missing[@]} -gt 0 ]; then
  echo "Specboards needs:" >&2
  printf '  - %s\n' "${missing[@]}" >&2
  exit 1
fi
if ! docker info >/dev/null 2>&1; then
  echo "Docker is installed but not running. Start Docker and try again." >&2
  exit 1
fi

# The database's host port: an override on this run wins, else whatever a
# previous run recorded, else the default. Read before the checks below so a
# stack already moved off 5432 is checked on the port it actually uses.
recorded_port=""
if [ -f "$env_file" ]; then
  recorded_port="$(sed -n 's/^POSTGRES_PORT=//p' "$env_file" | tr -d '"' | head -1)"
fi
web_port=3000
db_port="${POSTGRES_PORT:-${recorded_port:-5432}}"

# Ports, before the build rather than after it. A machine with its own Postgres
# on 5432 is the common case, and compose's own failure for this arrives several
# minutes in and names a container rather than a fix.
#
# Skipped when this stack is already up, because then the thing holding the
# ports is us, and re-running ./setup.sh on a running instance has to stay a
# safe no-op rather than a confusing refusal.
port_busy() {
  if command -v lsof >/dev/null 2>&1; then
    lsof -nP -iTCP:"$1" -sTCP:LISTEN >/dev/null 2>&1
  else
    # No lsof (many slim Linux images): try to open the port instead.
    (exec 3<>"/dev/tcp/127.0.0.1/$1") 2>/dev/null && { exec 3<&-; return 0; }
    return 1
  fi
}

if [ -z "$("${compose[@]}" ps -q 2>/dev/null)" ]; then
  if port_busy "$web_port"; then
    echo "Port $web_port is already in use, and Specboards serves on it." >&2
    echo "Stop whatever is using it, then re-run ./setup.sh." >&2
    exit 1
  fi
  if port_busy "$db_port"; then
    echo "Port $db_port is already in use (often another Postgres)." >&2
    echo "Re-run with a free port, e.g.:" >&2
    echo "    POSTGRES_PORT=55432 ./setup.sh" >&2
    echo "Only the host side moves; nothing inside the stack changes." >&2
    exit 1
  fi
fi

# --- secrets ----------------------------------------------------------------
# BETTER_AUTH_SECRET has no default anywhere and compose refuses to start
# without it, so a first run has to produce one. Generated here rather than
# asked for: a secret a human pastes from a tutorial is worse than one nobody
# has ever seen, and "run openssl and edit a file" was a step people stopped on.
random_hex() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex "$1"
  else
    # Every machine that can run Docker has one of these; do not require openssl.
    head -c "$1" /dev/urandom | od -An -tx1 | tr -d ' \n'
  fi
}

if [ ! -f "$env_file" ]; then
  echo "Creating $env_file with generated secrets…"
  umask 077
  cat > "$env_file" <<EOF
# Generated by ./setup.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ). Keep this file secret.
#
# Rotating BETTER_AUTH_SECRET signs everyone out AND makes anything encrypted
# under the old key unreadable (the GitHub App private key, webhook signing
# secrets, each workspace's model provider key). Treat it as a migration.
BETTER_AUTH_SECRET=$(random_hex 32)

# Baked into the database volume on first start. Changing it later means
# ALTER USER in psql, not just editing this file.
POSTGRES_PASSWORD=$(random_hex 24)

# Public origin of this deployment. The default suits a local trial. Set this
# to a real HTTPS origin before anyone else can reach the instance.
APP_URL=http://localhost:3000

# Host port the database is published on, loopback only. Move it if something
# else already owns 5432; only the host side changes.
POSTGRES_PORT=${db_port}

# Outbound email (verification, password reset, invites). Unset means email is
# skipped; sign-up then does not require verification, because the link could
# never arrive. Set both to turn real verification on.
# POSTMARK_SERVER_TOKEN=
# EMAIL_FROM=Specboards <no-reply@example.com>
EOF
  echo "  secrets generated; this file is not overwritten on later runs."
else
  echo "Using existing $env_file."
fi

# --- build, migrate, start --------------------------------------------------
# There is no published image yet, so the first run builds one and takes a few
# minutes. `up` waits on the migrate service, which waits on the database being
# healthy, so by the time this returns the schema exists.
echo "Building and starting (first run takes a few minutes)…"
# Explicit rather than inherited: a POSTGRES_PORT passed on this script's
# command line has to reach compose, and one already recorded in infra/.env is
# read from there.
export POSTGRES_PORT="$db_port"
"${compose[@]}" up -d --build

url="$(grep -E '^APP_URL=' "$env_file" | cut -d= -f2- | tr -d '"' || true)"
url="${url:-http://localhost:3000}"

# Wait for the app to actually answer rather than declaring victory on `up`.
echo -n "Waiting for Specboards to answer"
for _ in $(seq 1 60); do
  if curl -fsS -o /dev/null "http://localhost:3000/" 2>/dev/null; then
    echo
    echo
    echo "Specboards is running at $url"
    echo "Open it and create your account; the first account becomes the admin."
    echo
    echo "  ./setup.sh --stop      stop, keep data"
    echo "  ./setup.sh --destroy   stop and delete the database"
    exit 0
  fi
  echo -n "."
  sleep 2
done

echo
echo "The stack started but nothing answered on :3000 within two minutes." >&2
echo "Check the logs with: docker compose -f infra/docker-compose.yml logs web" >&2
exit 1
